"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
from shutil import copyfile
import os
import sys
sys.setrecursionlimit(10 ** 9)

VERSION = '0.2.0'
VERSION_PYTHON = '{0}.{1}'.format(sys.version_info.major, sys.version_info.minor)
APP_NAME = 'weighing_calculator'
DESCRIPTION = "Calculate weghing."
AUTHOR = 'yu-9824'

'''
メモ
/.pyenv/versions/anaconda3-2019.03/envs/pymat/lib/python3.7/site-packages/PyQt5/uic/port_v2/ascii_upper.pyの28行目を書き換えた．
少なくともpython3.7においてstringオブジェクトはmaketrans関数を持っておらず，正しくはstr.maketransである．
python3.8で以前やったときはこのエラーがでなかった．
* 3.8にアップデートしてやってみる．
    →3.8だとsetupのほうがエラー起きるので3.6でやってみる．
    3.6は起動後に関数が呼び出せないと言われる
'''

if 'py2app' in sys.argv:
    alias = '-A' in sys.argv

    # 諸変数・定数の定義
    APP = ['main.py']
    DATA_FILES = []
    lib_path = os.path.join(os.environ['CONDA_PREFIX'], 'lib')

    # libpython3.7.m.dylibだとエラーになるのであらかじめコピーしておく．
    path_original = os.path.join(lib_path, 'libpython{}m.dylib'.format(VERSION_PYTHON))
    path_converted = os.path.join(lib_path, 'libpython{}.dylib'.format(VERSION_PYTHON))
    if os.path.exists(path_original) and not os.path.exists(path_converted):
        copyfile(path_original, path_converted)

    # 諸変数の準備
    dylib_files = [os.path.join(lib_path, f) for f in os.listdir(lib_path) if '.dylib' in f]
    frameworks_path = 'dist/' + APP_NAME + '.app/Contents/Frameworks'

    PKGS = ['pandas', 'numpy', 'xlwt', 'element_recognition', 'PySimpleGUI', 'pymatgen', 'openpyxl']

    OPTIONS = {
        'argv_emulation': False,
        'packages': PKGS,
        'iconfile': 'icon/{}.icns'.format(APP_NAME),
        'plist':{
            'PyRuntimeLocations':[
                '@executable_path/../Frameworks/libpython{}.dylib'.format(VERSION_PYTHON),
                os.path.join(lib_path, 'libpython{}.dylib'.format(VERSION_PYTHON)),
            ],
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': DESCRIPTION,
            'CFBundleIdentifier': "com.{0}.osx.{1}".format(AUTHOR, APP_NAME),
            'CFBundleVersion': VERSION,
            'CFBundleShortVersionString': VERSION,
            'NSHumanReadableCopyright': u"Copyright © 2021, {}".format(AUTHOR)
        },
        'frameworks': dylib_files,
    }

    setup(
        name=APP_NAME,
        app=APP,
        author='yu-9824',
        version = VERSION,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )
    # if not alias:
    #     {copyfile(f, os.path.join(frameworks_path, os.path.basename(f))) for f in dylib_files}
else:
    with open('requirements.txt') as requirements_file:
        install_requirements = requirements_file.read().splitlines()

    setup(
        name=APP_NAME,
        version=VERSION,
        description=DESCRIPTION,
        author=AUTHOR,
        author_email='yu.9824@gmail.com',
        install_requires=install_requirements,
        url='https://github.com/yu-9824/weighing_calculator',
        license=license,
        packages=find_packages(exclude=['example'])
    )
